[project]
name = "the-green-dilemma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame-ce>=2.5.6",
    "pytest>=9.0.2",
    "ruff>=0.15.0",
]
